name: Build Go

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install @semantic-release/git @semantic-release/changelog @semantic-release/exec

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --ci

      - name: Build the Docker image
        id: build
        run: docker build -t docker.pkg.github.com/${{ github.repository }} /sensi:latest -t docker.pkg.github.com/${{ github.repository }} /sensi:${{ steps.release.outputs.version }} --build-arg VERSION=${{ steps.release.outputs.version }} .

      - name: Docker login
        run: docker login docker.pkg.github.com -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.GITHUB_TOKEN}}

      - name: Publish to CR
        run: |
          docker push "docker.pkg.github.com/${{ github.repository }} /sensi:latest"; \
          docker push "docker.pkg.github.com/${{ github.repository }} /sensi:${{ steps.release.outputs.version }}"
