name: Build Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - run: git fetch --prune --unshallow

      - name: Build the Docker image
        id: build
        run: |
          docker build -t sensi:latest . | tee .logs; \
          echo "::set-output name=semver::$(cat .logs | grep ^SEMVER | cut -d ":" -f2)"; \
          rm .logs

      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag the version on git
        run: |
          git tag -fa v${{ steps.build.outputs.semver }} -m "Version: ${{ steps.build.outputs.semver }}"; \
          git push origin v${{ steps.build.outputs.semver }}
