name: Build Go

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog@3.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        id: build
        run: docker build -t sensi:latest -t sensi:${{ steps.release.outputs.new_release_version }} --build-arg VERSION=${{ steps.release.outputs.new_release_version }} .
